print("{:^11}\n".format('*'))
print("{:^11}\n".format('***'))
print("{:^11}\n".format('*****'))
print("{:^11}\n".format('*******'))
print("{:^11}\n".format('*********'))
print("{:^11}\n".format('***********'))
